version: 2.1
orbs:
  slack: circleci/slack@3.4.0
  maven: circleci/maven@1.0.3

jobs:
  build_test_norify:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      #      - maven/test
      - run:
          name: install maven and execute
          command: |
            mvn install
            mvn verify
            echo 'agregando el reporte generado por serenity'
#      - store_test_results:
#          path: ~/test-results
#      - store_artifacts:
#          path: ~/test-results/junit
#      - persist_to_workspace:
#          root: .
#          paths:
#            - ProyectoApiRest/target

workflows:
  build_test_norify:
    jobs:
      - build_test_norify